01-31-16 AM:DEBUG [logger_base.py:14] Mensaje a nivel debug
01-31-16 AM:INFO [logger_base.py:15] Mensaje a nivel info
01-31-16 AM:WARNING [logger_base.py:16] Mensaje a nivel warning
01-31-16 AM:ERROR [logger_base.py:17] Mensaje a nivel error
01-31-16 AM:CRITICAL [logger_base.py:18] Mensaje a nivel critical
03-22-34 AM:ERROR [conexion.py:67] Ocurrio un error al obtener el pool:
03-29-15 AM:ERROR [conexion.py:67] Ocurrio un error al obtener el pool:
03-29-47 AM:DEBUG [cursor_del_pool.py:10] Inicio del método with y __enter__
03-29-47 AM:ERROR [conexion.py:67] Ocurrio un error al obtener el pool:
03-38-26 AM:DEBUG [cursor_del_pool.py:11] Inicio del método with y __enter__
03-38-26 AM:ERROR [conexion.py:67] Ocurrio un error al obtener el pool:
03-38-45 AM:DEBUG [cursor_del_pool.py:11] Inicio del método with y __enter__
03-38-45 AM:ERROR [conexion.py:67] Ocurrio un error al obtener el pool:
03-39-54 AM:INFO [menu_app_usuario.py:37] Salimos de la aplicación. ¡Hasta pronto!
